---
- hosts: server1
  become: true
  pre_tasks:

  - name: Install update (Ubuntu)
    tags: always
    apt:
      update_cache: yes

- hosts: server1
  become: true
  tasks:

  - name: Collect log files from Server 1
    fetch:
      src: "/var/log/{{ item }}"
      dest: "s1_logs/"
      flat: yes
    with_items:
      - syslog
      - auth.log
